### ISSUE TITLE
random effects in brmultinom?

### ISSUE THREAD

**Issue by rebeccaltaylor** [ikosmidis/brglm2#13]
Hi.  I am trying unsuccessfully to add a random effect to a model in brmultinom.  I am not sure if the package does not support random effects, or if I am just coding it incorrectly.  I am using the following command:

Multi15_250 <- brmultinom(Behavior ~ PrevBehav + (1 | RandWal), data = BfrAftr15_25, ref = "Swm", type = "AS_mixed")

I get the following error:

Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels
In addition: Warning message:
In Ops.factor(1, RandWal) : ‘|’ not meaningful for factors

Thank you!

Rebecca

**Comment by ikosmidis** [comment]
Hi Rebecca,

brmultinom supports only fixed-effects models at this stage, I am afraid.

**Comment by rebeccaltaylor** [comment]
Thank you
