### ISSUE TITLE
AIC appears to be -2*loglik without parameter penalty

### ISSUE THREAD

**Issue by rebeccaltaylor** [ikosmidis/brglm2#14]
Is there a chance you forgot to add the parameter penalty when calculating AIC?  For example, in a model I fit called Multi15_25.1, that I summarized in the object SmryMulti15_25.1, when I call SmryMulti15_25.1$AIC , it returns 543.0035.  When I call SmryMulti15_25.1$logLik, it returns 'log Lik.' -271.5017 (df=6).  And -2*(-271.5017) = 543.0035.

Also, can you please tell me what is the number the package calls "aic"?  It is different than what the package calls "AIC." 

Thank you.

Rebecca

**Comment by ikosmidis** [comment]
Thanks. That was a minor bug which is now fixed in the develop branch and will appear in the next release. You may install the current development version by

```r
remotes::install_github("ikosmidis/brglm2", ref = "develop")
```

or simply extract AIC values in the current version directly by `AIC(Multi15_25.1)`
