### ISSUE TITLE
"likelihood ratio test" with output from brmultinom

### ISSUE THREAD

**Issue by rebeccaltaylor** [ikosmidis/brglm2#18]
After fitting two models with brmultinom using type = "AS_mixed" to handle quasi-complete separation,  is it appropriate for me to test for differences in the same manner in which I would construct a LRT? 

For example, I fit models "BRM0" and "BRM", used the anova command and compared the results to a chi-squared distribution as follows:

anova(BRM0,BRM)
#       Resid. Df Resid. Dev Df Deviance
# 1      1748     592.95            
# 2      1746     593.67      2 -0.72255

pchisq(-0.72255,df=2,lower.tail = FALSE)

Could you kindly know if this is appropriate, and if so, what to call it?

Thank you!!

Rebecca

**Comment by ikosmidis** [comment]
Can you provide a reproducible example? The answer to this question depends on what BRM and BRM0 are.

**Comment by rebeccaltaylor** [comment]
``` r
library(brglm2); library(reprex)

## All models are 3-category nominal, multinomial (with no overdispersion).
## The response variable is "aBehavior". The effect I am testing for
## significance is a binary treatment ("Trt15_25_5min").
## Some models have covariates; others do not. Covariates may be continuous
## or categorical and they may interact with each other. There are no
## interactions with treatment. I provide 2 example tests below.
```

``` r
## Comparison 1: treatment effect vs intercept only model

SmallFrm <- data.frame(Trt15_25_5min = as.factor(c(0,0,0,1,1,1)), 
                       aBehavior = as.factor(c("aSwm", "For", "HO", "aSwm", "For", "HO")), 
                       Ncases = c(81,702,1,12,86,0)) 
SmallFrm
#>   Trt15_25_5min aBehavior Ncases
#> 1             0      aSwm     81
#> 2             0       For    702
#> 3             0        HO      1
#> 4             1      aSwm     12
#> 5             1       For     86
#> 6             1        HO      0

BRM0 <- brmultinom(aBehavior ~ 1, data = SmallFrm, ref = "aSwm", weights = Ncases) 
BRM <- brmultinom(aBehavior ~ Trt15_25_5min, data = SmallFrm, ref = "aSwm", weights = Ncases) 
anova(BRM0,BRM)
#> Analysis of Deviance Table
#> 
#> Model 1: aBehavior ~ 1
#> Model 2: aBehavior ~ Trt15_25_5min
#>   Resid. Df Resid. Dev Df Deviance
#> 1         8     609.78            
#> 2         6     610.23  2 -0.44448
pchisq(-0.44448,df=2,lower.tail = FALSE)
#> [1] 1
```

``` r
## Comparison 2: base model has one continuous covariate ("Temp") which 
## interacts with one 3-category factor ("ThreeSubstr") and one binary 
## factor ("HasPrvBoutHrFor"). The LRT is again for significance of the 
## treatment effect ("Trt15_25_5min") on the respone ("aBehavior). Each 
## model below takes ~2 min to run. Please change to your directory the
## path named 'ChangeToYourDirectory'. The data file is attached to this 
## post. I'm sorry but I don't know any other way to do this. Thank you.

ChangeToYourDirectory <- "D:/docs/Vessel interactions/data/from Bill/Aug 2019 data but reverting to matched analyses March 2020/Rad15_25 5min exposure/main8_trimmed/For"
ForSub <- read.csv(paste0(ChangeToYourDirectory,"/ForSub.csv"), stringsAsFactors = TRUE, row.names = 1)
summary(ForSub)
#>       Temp          HasPrvBoutHrFor  Trt15_25_5min    aBehavior  ThreeSubtr
#>  Min.   :-9.23106   Min.   :0.0000   Min.   :0.0000   aSwm: 93   IO :432   
#>  1st Qu.: 0.06734   1st Qu.:1.0000   1st Qu.:0.0000   For :788   LO : 27   
#>  Median : 0.74965   Median :1.0000   Median :0.0000   HO  :  1   NIL:423   
#>  Mean   : 0.56027   Mean   :0.9444   Mean   :0.1111                        
#>  3rd Qu.: 1.29663   3rd Qu.:1.0000   3rd Qu.:0.0000                        
#>  Max.   : 4.58817   Max.   :1.0000   Max.   :1.0000

BRM0 <- brmultinom(aBehavior ~ Temp*ThreeSubtr + Temp*HasPrvBoutHrFor, data = ForSub, ref = "aSwm")
BRM <- brmultinom(aBehavior ~ Trt15_25_5min + Temp*ThreeSubtr + Temp*HasPrvBoutHrFor, data = ForSub, ref = "aSwm") 
anova(BRM0,BRM)
#> Analysis of Deviance Table
#> 
#> Model 1: aBehavior ~ Temp * ThreeSubtr + Temp * HasPrvBoutHrFor
#> Model 2: aBehavior ~ Trt15_25_5min + Temp * ThreeSubtr + Temp * HasPrvBoutHrFor
#>   Resid. Df Resid. Dev Df Deviance
#> 1      1748     592.95            
#> 2      1746     593.67  2 -0.72255
pchisq(-0.72255,df=2,lower.tail = FALSE)
#> [1] 1
```

<sup>Created on 2020-06-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

[ForSub.zip](https://github.com/ikosmidis/brglm2/files/4747704/ForSub.zip)

**Comment by rebeccaltaylor** [comment]
Hi.

I believe the example I provided on Github is clear and reproducible.  If not, please let me know and I will do whatever I need to make it better.

Thank you!

Rebecca

________________________________

**Comment by ikosmidis** [comment]
Thanks for the example. It looks fine. I hope to respond to you in the next few days.

**Comment by ikosmidis** [comment]
#9

**Comment by rebeccaltaylor** [comment]
I'm sorry, but I don't understand the response......

**Comment by ikosmidis** [comment]
That's not a response. Rather a note to me that this relates to issue #9

**Comment by rebeccaltaylor** [comment]
Ah, ok--thank you!

________________________________

**Comment by ikosmidis** [comment]
The log-likelihood ratio statistic at the reduced-bias estimates is asymptotically equivalent to the usual log-likelihood ratio statistic (at the maximum likelihood estimates). Hence, `anova` results are asymptotically correct. However, in finite samples, the log-likelihood ratio statistic at the reduced biased estimates can take negative values, and you have very well reproduced an example of that. Thanks.

This is because the penalized likelihoods that are maximized for `aBehavior ~ 1` and `aBehavior ~ Trt15_25_5min` have different penalties. More specifically, the model matrix used in the bias-reducing Jeffreys' prior penalty for `aBehavior ~ 1` is only part of the model matrix used for `aBehavior ~ Trt15_25_5min`; see [Kosmidis & Firth (2011)](https://www.jstor.org/stable/23076146) and  [Bull et al (2002, Section 3.2)](https://www.sciencedirect.com/science/article/abs/pii/S0167947301000482) for more details.

There are ways around that, as use of penalized likelihood ratio statistics, adjusted score statistics and wald statistics for model comparison, which I plan to implement in the next major release of brglm2 (issues #9). 

Wald tests and score tests as implemented by the `lmtest` R package for example work fine for `brglm2` objects (i.e. ones that result by doing `glm(..., method = "brglm_fit")` but not for `brmultinom` (and `bracl`) objects.

In the meantime, it is correct to use the maximum likelihood fits for model comparison, i.e.
```r
M0 <- brmultinom(aBehavior ~ 1, data = SmallFrm, ref = "aSwm", weights = Ncases, type = "ML")
M <- brmultinom(aBehavior ~ Trt15_25_5min, data = SmallFrm, ref = "aSwm", weights = Ncases, type = "ML")
anova(M0, M, test = "Chisq")
#> Analysis of Deviance Table
#>
#> Model 1: aBehavior ~ 1
#> Model 2: aBehavior ~ Trt15_25_5min
#>  Resid. Df Resid. Dev Df Deviance Pr(>Chi)
#> 1         8     609.59                     
#> 2         6     609.04  2  0.55608   0.7573
```
The ML estimates are infinite for one of the models, but the values of the maximized likelihoods (and hence the residual deviances) are very close to their actual values! You can then report the (finite!) reduced-bias estimates (i.e. from BRM0 and BRM) if you need to report those, too.

BTW, I recommend using the `anova` interface to compute p-values. For example,  you can clearly see that the output does not report a p-value, despite that this is explicitly requested. This is because the deviance is negative (and positive is expected for likelihood ratio tests) and `anova` does not know how to handle this.
```r
BRM0 <- brmultinom(aBehavior ~ 1, data = SmallFrm, ref = "aSwm", weights = Ncases)
BRM <- brmultinom(aBehavior ~ Trt15_25_5min, data = SmallFrm, ref = "aSwm", weights = Ncases)
anova(BRM0, BRM, test = "Chisq")
#> Analysis of Deviance Table
#>
#> Model 1: aBehavior ~ 1
#> Model 2: aBehavior ~ Trt15_25_5min
#>  Resid. Df Resid. Dev Df Deviance Pr(>Chi)
#> 1         8     609.78                     
#> 2         6     610.23  2 -0.44448         
```

**Comment by rebeccaltaylor** [comment]
Hello.

First, thank you so much for your detailed and helpful answer! Using the ML-based LRT but the bias corrected estimates will work perfectly for me.  And I am totally embarrassed that I missed the LRT statistic being negative!!!

If you don't mind, I do have two other questions.  

I found a Wald test in lmtest, but not a score test--am I missing something? Any chance you were thinking about the mdscore package?

Finally, I hope you don't mind my asking your advice regarding LRTs when quasi-likelihood methods are used (e.g. MQL, PQL, but to implement random effects models, not to deal with complete separation). I have been advised to simulate p-values based on the LRT statistic constructed with the values obtained via the quasi-likelihood method. I believe this will work if the maximized values are biased, but not also imprecise. And it seems the same would apply to results from brmultinom if there weren't already a good solution.  Do you concur with this advice? I am simply asking as a second opinion, as you and the other person advising me are both vastly more knowledgeable than am I.

Thank you again for your time and help--it would have taken me a very long time to figure this out on my own!!

Rebecca

**Comment by ikosmidis** [comment]
> I found a Wald test in lmtest, but not a score test--am I missing something? Any chance you were thinking about the mdscore package?

Err sorry. Indeed. You should look at the help file of `anova.glm` for the Rao test (which is the score test)

> 
> Finally, I hope you don't mind my asking your advice regarding LRTs when quasi-likelihood methods are used (e.g. MQL, PQL, but to implement random effects models, not to deal with complete separation). I have been advised to simulate p-values based on the LRT statistic constructed with the values obtained via the quasi-likelihood method. I believe this will work if the maximized values are biased, but not also imprecise. And it seems the same would apply to results from brmultinom if there weren't already a good solution. Do you concur with this advice? I am simply asking as a second opinion, as you and the other person advising me are both vastly more knowledgeable than am I.
> 

I'm afraid I do not have any good advice to give on this (also please bear in mind that this area is for software issues). You can try stackoverflow for general questions like this

> Thank you again for your time and help--it would have taken me a very long time to figure this out on my own!!

Feel free to report any issues with brglm2!

**Comment by rebeccaltaylor** [comment]
Thank you!!

________________________________
