### ISSUE TITLE
Bias reduced logistic regression model estimation with one parameter produces NA

### ISSUE THREAD

**Issue by pziet** [ikosmidis/brglm2#20]
[PZIET-brglm2_bug.txt](https://github.com/ikosmidis/brglm2/files/4896548/PZIET-brglm2_bug.txt)

When using `brglmFit()` for a logistic regression with one coefficient, `NA` is returned. However using `brglm()` from the `brglm` package returns a real valued coefficient. The code snippet below illustrates this issue, 
```
# Author: Patrick Zietkiewicz
# File purpose: Investigate possible bug in brglm2 package
library(brglm)
library(brglm2)
dat <- MASS::Pima.tr
X <- as.matrix(dat[,1:7])
Y <- as.matrix(dat[,'type'] == 'Yes', 1, 0)
# fit models
res_brglm <- brglm(Y ~ -1 + X[,'bmi'],
                 family = binomial(link='logit'),
                 pl = FALSE)
res_brglm2 <- brglmFit(x = X[,'bmi'], y = Y, 
        family = binomial(link='logit'),
        intercept = FALSE)
cat('brglm:', res_brglm$coefficients,'\n')
cat('brglm2:', res_brglm2$coefficients,'\n')
cat('done')
```
Please see the attached txt file for a copy of the code snippet above

**Comment by ikosmidis** [comment]
Thanks! This is a minor bug and happens when the input is a vector (i.e. no column names). For example, 
```r
brglmFit(x = X[,'bmi', drop = FALSE], y = Y, family = binomial(link='logit'), intercept = FALSE)
```
works as expected. Will be fixed in next release.
