### ISSUE TITLE
brglm2 algorithm does not converge

### ISSUE THREAD

**Issue by cccccccH** [ikosmidis/brglm2#23]
Hi Dr. kosmidis,

I got two warning message when I fit a logistic regression with one covariate, no intercept.
1: brglmFit: algorithm did not converge 
2: brglmFit: fitted probabilities numerically 0 or 1 occurred 
I got no problem when fitting standard logistic regression but got this problem when I use type = "MPL_Jeffreys".

Just a dataset with 50 samples and it look like this
![image](https://user-images.githubusercontent.com/74334272/104382263-cd21c900-54fb-11eb-9a0a-1d8bd71fbd18.png)

I hope to understand what might happen here. Thank you.

**Comment by ikosmidis** [comment]
Thanks. Can you please share some code that fully reproduces this issue? [reprex](https://reprex.tidyverse.org) can help.

**Comment by cccccccH** [comment]
The issue reported here is using brglm2. I tried JeffreysMPL function provided in this paper "Jeffreys-prior penalty, finiteness and shrinkage in binomial-response generalized linear models". It successfully fits.  I am wondering what is the difference of JeffreysMPL and brglm2 with type = "MPL_Jeffreys".  Thanks!

**Comment by ikosmidis** [comment]
They do the same thing (maximum the penalised likelihood with a Jeffreys prior penalty) but using different algorithms. I am still interested in a reproducible example of the issues you describe here, as there may be a small bug in brglm2. Let me know if you want to provide that, otherwise I will consider this issue resolved.

**Comment by ikosmidis** [comment]
Closing this issue. Please consider re-opening with a reproducible example, if necessary.
