### ISSUE TITLE
The variables responsible on the separation are not shown 

### ISSUE THREAD

**Issue by IlhemB** [ikosmidis/brglm2#27]
I want to test the separation, so I used this code : 

glm(MODEL_FORM_GLM, data=train_std, family = binomial("logit"),method = "detect_separation")

As you can see below this does not show the variables responsible for the separation. 

Implementation: | Linear program: | Purpose: 
Separation: TRUE 
Warning message:
'detect_separation' will be removed from 'brglm2' at version 0.8. A new version of 'detect_separation' is now maintained in the 'detectseparation' package.

**Comment by ikosmidis** [comment]
Please send a fully-reproducible including `train_std` and `MODEL_FOR_GLM` and I can investigate. All internal tests pass.

**Comment by ikosmidis** [comment]
Closing as this has been inactive for a while now.
