### ISSUE TITLE
brglmFit() and brglm_fit() broken for hello world

### ISSUE THREAD

**Issue by twest820** [ikosmidis/brglm2#28]
```r
data = tibble(x = rnorm(n = 100), y = rbinom(n = 100, size  = 1, prob = 0.3))
brglmFit(y ~ x, data)
# Error in dim(data) <- dim : 
#  invalid first argument, must be vector (list or atomic)
brglm_fit(y ~ x, data)
# Error in dim(data) <- dim : 
#  invalid first argument, must be vector (list or atomic)
dim(data)

brglmFit(y ~ x, data, family = "binomial")
# Error: $ operator is invalid for atomic vectors
brglm_fit(y ~ x, data, family = "binomial")
# Error: $ operator is invalid for atomic vectors

# same call works in v1 even though v2 indicates it's ready to supersede v1
brglm(y ~ x, data, family = "binomial")

Call:  brglm(formula = y ~ x, family = "binomial", data = data) 

Coefficients:
(Intercept)            x  
   -0.87187     -0.08554  

Degrees of Freedom: 99 Total (i.e. Null);  98 Residual
Deviance:	    120.2965 
Penalized Deviance: 114.2566 	AIC: 124.2965
```

**Comment by ikosmidis** [comment]
See `?brglmFit` where it is explained that `brglmFit()` is a method for `glm()`. For your example, you need

```glm(y ~ x, family = binomial(), data = data, method = "brglmFit")```

**Comment by twest820** [comment]
Thank you for the clarification!

I don't think it's entirely correct to close the issue, however.

1. The error messages are not informative or user actionable.
2. The usage given in the documentation for `brglmFit()` is *quite* different from the correct syntax. The bit about glm(method = "glm.fit") is buried in the examples. While I'm sure some users will get all the way to examples, a reasonable interpretation when updating an existing call of `brglm()` is simply that function's been renamed to `brglmFit()`.

It's probably desirable to make code changes in argument validation and revise the documentation for clarity.

**Comment by ikosmidis** [comment]
1. The error messages you get are because you are supplying a formula to a function that, according to its documentation, expects its first argument to be a matrix/vector. Yes, I can guard against this but this is what the error message tells you anyway. Try `glm.fit(y ~ x, data)` (`glm()`'s default fitting method) and you will see that you get the same error.

2. Please explain. The examples have the same structure as the resolution I provided above.

**Comment by ikosmidis** [comment]
If you still wish to propose documentation or argument handling improvements, please feel free to open new issues. This issue, as titled and described, has been resolved in my first response.
