### ISSUE TITLE
Support for Ordered Logistic Regression (cumulative family object)

### ISSUE THREAD

**Issue by FinBauer** [ikosmidis/brglm2#32]
Does brglm2 currently support ordered logistic regression? I had no luck trying to pass a cumulative() family object to brglmFit.

Thank you for the great package!

Fin

**Comment by ikosmidis** [comment]
Hi Fin, I gather you mean cumulative link model with logistic link; unfortunately, these are not supported in brglm2 yet but they will be soon. 

My paper on those models

[Kosmidis I (2014). Improved estimation in cumulative link models. Journal of the Royal Statistical Society: Series B, 76, 169-196 ](http://doi.org/10.1111/rssb.12025)

came with [supplementary material](http://ikosmidis.com/files/rssb12025-sup-0002-supplementary-materials-ikosmidis.zip), which has code to fit ordered logistic regression models, and examples of how to do so. Feel free to get in touch by email (not a brglm2 issue) if you need anyhelp with that codebase.

**Comment by ikosmidis** [comment]
You may also want to take a look at the `bracl()` function in brglm2 which can fit adjacent category logit models (another module class for ordinal responses).

**Comment by FinBauer** [comment]
Thank you so much for your quick help! Unfortunately, `bracl()` doesn't work for my purposes, I will check out the supplementary material of your paper!
