### ISSUE TITLE
Support for quasi... families?

### ISSUE THREAD

**Issue by tomwenseleers** [ikosmidis/brglm2#35]
I was just wondering if it would also be possible to support quasipoisson & quasibinomial? Or is there any currently supported method to take into account overdispersion in binomial GLMs?

**Comment by ikosmidis** [comment]
Hi @tomwenseleers: thanks. My [brquasi](https://github.com/ikosmidis/brquasi) package (still in beta, sorry) provides this functionality. See also my [eRum 2020 presentation](https://ikosmidis.com/files/ikosmidis_brquasi_eRum2020/#1).

Feel free to open issues on the brquasi GitHub page. This is still beta, so I am keen to quickly implement issues / add features  and fix things
