### ISSUE TITLE
family = "gaussian" does not seem to work

### ISSUE THREAD

**Issue by bpuladi** [ikosmidis/brglm2#37]
First of all, thank you for your great work! I have tried your package. It seems to work for glm with family = "binomial". For the family = "gaussian", almost the same coefficients are generated when comparing standard glm and a glm with method = "brglmFit", type="correction". The difference in the coefficients is less than 10^-13. I guess there is something wrong with the link function and the calculation of the coefficients?

**Comment by ikosmidis** [comment]
You are welcome! Glad you find it useful. Accepting the model you are trying to fit as appropriate, there is no mean or median bias to correct when family = "gaussian" (linear regression with normal iid errors), hence, `glm.fit` and `brglm_fit` return the same output (up to numerical accuracy). I hope this helps!
