### ISSUE TITLE
"detect_separation" failed

### ISSUE THREAD

**Issue by dasiav7** [ikosmidis/brglm2#5]
`glm(Histology ~ Cigarette + med1 * med2 * med3 * med4 + Age + Gender + Stage + Race, family = binomial("logit"), data = data2, method = "detect_separation")
`

gives：

`Error in separator(x = x, y = y, linear_program = control$linear_program,  : 
  unexpected result from lpSolveAPI for primal test
`

[data2.zip](https://github.com/ikosmidis/brglm2/files/1103038/data2.zip)

**Comment by ikosmidis** [comment]
It looks like the primal test fail. The dual program works:

```
R> library(brglm2)
R> load("data2.rda")
R> form2 <- Histology ~ Cigarette + med1 * med2 * med3 * med4 + Age + Gender + Stage + Race
R> glm(form2, family = binomial("logit"), data = data2, method = "detect_separation", linear_program = "dual")
Separation: FALSE 
Existence of maximum likelihood estimates
          (Intercept) Cigarettenot reported          CigaretteYes 
                    0                     0                     0 
                 med1                  med2                  med3 
                    0                     0                     0 
                 med4               Age>=75              Age55-64 
                    0                     0                     0 
             Age65-74       Agenot reported            Gendermale 
                    0                     0                     0 
              StageII              StageIII               StageIV 
                    0                     0                     0 
    Stagenot reported                RaceNo      Racenot reported 
                    0                     0                     0 
            med1:med2             med1:med3             med2:med3 
                    0                     0                     0 
            med1:med4             med2:med4             med3:med4 
                    0                     0                     0 
       med1:med2:med3        med1:med2:med4        med1:med3:med4 
                    0                     0                     0 
       med2:med3:med4   med1:med2:med3:med4 
                    0                     0 
0: finite value, Inf: infinity, -Inf: -infinity
```

A post-fit check for infinite estimates agrees with the above. Specifically, there are no diverging standard errors across IWLS iterations, and hence no evidence for infinite maximum likelihood estimates

```
R> m_glm <- glm(form2, family = binomial("logit"), data = data2)
R> matplot(check_infinite_estimates(m_glm), type = "l", col = "black", lty = 1)
```
Does this help? Please re-open issue if not

**Comment by dasiav7** [comment]
Dear Dr. ikosmidis,

Thank you! What's the difference between "primal" and "dual" in the program?

**Comment by ikosmidis** [comment]
See `?detect_separation_control` and `?detect_separation`. For details on the linear programs for detecting separation, pre-fit, see

Kjell Konis (2007). *Linear Programming Algorithms for Detecting Separated Data in Binary Logistic Regression Models*. DPhil. University of Oxford. <URL:  https://ora.ox.ac.uk/objects/uuid:8f9ee0d0-d78e-4101-9ab4-f9cbceed2a2a>
