### ISSUE TITLE
brmultinom errors

### ISSUE THREAD

**Issue by CMPinciotti** [ikosmidis/brglm2#7]
I am attempting to run a multinomial regression that has 3 levels of the categorical DV (reference category = 1) with a correction for data separation. I continue to receive an error that package ‘brglmfit’ is not available (for R version 3.6.1) and have attempted to run the analysis with package brglm2 instead. However, now with the below pasted syntax, I am getting the following error: Error in eval(extras, data, env) : object 'Freq' not found.

When I remove the weights = Freq syntax, the analysis simply doesn't run and does not give an error message.

brmultinomModel <- brmultinom(OCDPTSD3 ~ PCLintrusion+PCLavoidance+PCLcognitions+PCLarousal+DOCScontam+DOCSresponsibility+ 
                      DOCSunacceptablethts+DOCSjustright+LECSexAssault+LECCausedHarm, weights = Freq, 
                       data = OCD_PTSD_valid_n_595_1, type = "AS_mean", ref = 1)

[OCD-PTSD valid n = 595_1.xlsx](https://github.com/ikosmidis/brglm2/files/3577299/OCD-PTSD.valid.n.595_1.xlsx)

Thank you in advance for your help!

**Comment by ikosmidis** [comment]
Please submit a fully reproducible script, i.e. one that creates the object OCD_PTSD_valid_n_595_1 from OCD-PTSD valid n = 595_1.xlsx. 

Using reprex (https://reprex.tidyverse.org) would be best, as then I can also see the error.

**Comment by ikosmidis** [comment]
Closing this issue, as there has been no follow-up for while now. Consider re-opening is issue persists.
